import { useState } from 'react';
import { ThumbsUp, ThumbsDown, Sparkles, ExternalLink, TrendingUp, Rocket, Lightbulb, RefreshCw, Bookmark, FileText, Shield } from 'lucide-react';
import type { Post } from '../types';
import type { AppController } from '../hooks/useAppState';
import { timeAgo } from '../lib/format';

function formatExecutiveBody(text: string) {
  if (!text) return null;

  const keywords = ['EXECUTIVE SUMMARY', 'COMMENTS', 'WHY IT MATTERS', 'KEY TAKEAWAY'];
  const regex = new RegExp(`(${keywords.join('|')})`, 'i');
  const parts = text.split(regex);

  if (parts.length <= 1) {
    return <p className="t-body c-primary" style={{ fontSize: 16, lineHeight: 1.7, marginBottom: 28 }}>{text}</p>;
  }

  const sections: { title: string; content: string }[] = [];
  let currentTitle = 'EXECUTIVE SUMMARY';

  for (let i = 0; i < parts.length; i++) {
    const p = parts[i].trim();
    if (!p) continue;
    const match = keywords.find((k) => k.toLowerCase() === p.toLowerCase());
    if (match) {
      currentTitle = match;
    } else {
      sections.push({ title: currentTitle, content: p.replace(/^:\s*/, '') });
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14, marginBottom: 28 }}>
      {sections.map((sec, idx) => (
        <div key={idx} style={{ background: 'var(--bg-inset)', padding: '16px 20px', borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
          <div style={{ fontSize: 11, fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--accent)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>
            {sec.title}
          </div>
          <p className="t-body c-primary" style={{ fontSize: 15, lineHeight: 1.65 }}>
            {sec.content}
          </p>
        </div>
      ))}
    </div>
  );
}

export function Feed({ ctrl }: { ctrl: AppController }) {
  const { state, now, giveFeedback, toggleBookmark } = ctrl;
  const [loadingNext, setLoadingNext] = useState(false);

  const fetchNextQueuedNews = async () => {
    setLoadingNext(true);
    try {
      const agentId = localStorage.getItem('navarachna_agent_id');
      if (agentId) {
        const res = await fetch(`/api/agent/publish-next?agentId=${agentId}`, { method: 'POST' });
        if (res.ok) {
          const feedData = await res.json();
          if (feedData.posts && feedData.posts.length > 0) {
            const apiPosts: Post[] = feedData.posts.map((p: any) => ({
              id: p.id,
              topicId: p.id,
              title: p.topicTitle || 'Autonomous Intelligence Update',
              domain: state.persona?.domain || 'Robotics',
              tags: [state.persona?.domain || 'Robotics', 'Live Feed', 'Autonomous'],
              whatHappened: p.text,
              whyItMatters: 'Strategic alignment with continuous discovery and editorial evaluation.',
              whatCouldHappenNext: 'Ongoing autonomous scanning will evaluate further candidate topics.',
              aiInsight: 'AI Insight: Real-time intelligence processing from live Web RSS/arXiv sources.',
              rationale: {
                whySelected: p.rationale || 'High composite score in continuous discovery scan.',
                whyRelevantNow: 'Freshly published and evaluated.',
                selectedScore: 88,
                candidatesConsidered: 8,
                rejectedCount: 7,
              },
              sources: (p.sources || ['https://arxiv.org']).map((url: string) => ({ name: 'Live Web Source', url })),
              publishedAt: p.createdAt ? new Date(p.createdAt).getTime() : Date.now(),
              feedback: null,
            }));
            ctrl.state.posts = apiPosts;
            window.dispatchEvent(new Event('storage'));
          }
        }
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoadingNext(false);
    }
  };

  const activePost = state.posts[0];

  return (
    <div style={{ maxWidth: 1100, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 32 }} className="animate-fade-in">
      
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }} className="animate-slide-up">
        <div>
          <h1 className="t-h1 c-primary">Published Intelligence Feed</h1>
          <p className="t-body c-secondary" style={{ marginTop: 6 }}>
            Primary active report generated by autonomous continuous discovery and LLM evaluation.
          </p>
        </div>

        <button
          onClick={fetchNextQueuedNews}
          disabled={loadingNext}
          className="btn btn-primary"
          style={{ padding: '9px 18px', fontSize: 13, borderRadius: 10 }}
        >
          <RefreshCw size={14} className={loadingNext ? 'animate-spin' : ''} />
          {loadingNext ? 'Publishing Next...' : 'Advance Feed Queue'}
        </button>
      </div>

      {/* Main Card */}
      {!activePost ? (
        <div className="card animate-slide-up" style={{ padding: 48, textAlign: 'center' }}>
          <FileText size={32} className="c-muted" style={{ margin: '0 auto 12px' }} />
          <p className="t-body c-tertiary mono">No publications in feed yet. Continuous discovery engine running...</p>
        </div>
      ) : (
        <article className="card animate-slide-up" style={{ padding: 32, background: 'var(--bg-surface)', borderColor: 'var(--border-medium)', borderRadius: 18 }}>
          {/* Metadata Bar */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--border-subtle)', paddingBottom: 16, marginBottom: 24, flexWrap: 'wrap', gap: 12 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Sparkles size={16} className="c-accent" />
              <span className="t-label c-accent" style={{ letterSpacing: '0.05em' }}>PRIMARY PUBLISHED REPORT</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <span className="t-caption">{timeAgo(activePost.publishedAt, now)}</span>
              <span className="badge badge-cyan">Signal Score: {activePost.rationale.selectedScore}/100</span>
              <span className="badge badge-neutral">{activePost.domain}</span>
            </div>
          </div>

          {/* Title */}
          <h1 className="t-h1 c-primary" style={{ fontSize: 28, lineHeight: 1.3, marginBottom: 24 }}>
            {activePost.title}
          </h1>

          {/* Formatted Executive Summary Body */}
          {formatExecutiveBody(activePost.whatHappened)}

          {/* 3-Column Analysis Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16, marginBottom: 28 }}>
            <div style={{ background: 'var(--bg-inset)', padding: 20, borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
                <TrendingUp size={16} className="c-highlight" />
                <span className="t-label c-highlight">Strategic Value</span>
              </div>
              <p className="t-body c-secondary" style={{ fontSize: 14, lineHeight: 1.6 }}>{activePost.whyItMatters}</p>
            </div>

            <div style={{ background: 'var(--bg-inset)', padding: 20, borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
                <Rocket size={16} className="c-success" />
                <span className="t-label c-success">Trajectory &amp; Impact</span>
              </div>
              <p className="t-body c-secondary" style={{ fontSize: 14, lineHeight: 1.6 }}>{activePost.whatCouldHappenNext}</p>
            </div>

            <div style={{ background: 'var(--bg-inset)', padding: 20, borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
                <Lightbulb size={16} className="c-warning" />
                <span className="t-label c-warning">Autonomous Assessment</span>
              </div>
              <p className="t-body c-secondary" style={{ fontSize: 14, lineHeight: 1.6 }}>{activePost.aiInsight.replace('AI Insight: ', '')}</p>
            </div>
          </div>

          {/* Redesigned System Editorial Audit Box */}
          <div style={{ background: 'var(--bg-inset)', padding: 24, borderRadius: 16, border: '1px solid var(--border-subtle)', marginBottom: 28 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16, paddingBottom: 12, borderBottom: '1px solid var(--border-subtle)' }}>
              <Shield size={16} className="c-accent" />
              <span className="t-label c-accent" style={{ letterSpacing: '0.06em', fontWeight: 700 }}>SYSTEM EDITORIAL AUDIT</span>
            </div>

            {/* Why Selected — Full Width Hero Block */}
            <div style={{ background: 'var(--bg-card)', padding: 20, borderRadius: 12, borderLeft: '3.5px solid var(--accent)', border: '1px solid var(--border-subtle)', marginBottom: 16 }}>
              <div className="t-caption c-accent" style={{ fontWeight: 700, marginBottom: 8, letterSpacing: '0.05em' }}>WHY THIS TOPIC WAS SELECTED</div>
              <div style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, fontFamily: 'var(--font-sans)' }}>
                {activePost.rationale.whySelected}
              </div>
            </div>

            {/* 3-Column Metrics Row */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 12 }}>
              <div style={{ background: 'var(--bg-card)', padding: '16px 18px', borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
                <div className="t-caption c-tertiary" style={{ fontSize: 11, marginBottom: 4, fontWeight: 600 }}>RECENCY CONTEXT</div>
                <div className="t-meta c-primary" style={{ fontWeight: 600, fontSize: 13 }}>{activePost.rationale.whyRelevantNow}</div>
              </div>
              <div style={{ background: 'var(--bg-card)', padding: '16px 18px', borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
                <div className="t-caption c-tertiary" style={{ fontSize: 11, marginBottom: 4, fontWeight: 600 }}>CANDIDATES EVALUATED</div>
                <div className="t-meta c-primary" style={{ fontWeight: 600, fontSize: 13 }}>{activePost.rationale.candidatesConsidered} candidate topics</div>
              </div>
              <div style={{ background: 'var(--bg-card)', padding: '16px 18px', borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
                <div className="t-caption c-tertiary" style={{ fontSize: 11, marginBottom: 4, fontWeight: 600 }}>FILTERED CANDIDATES</div>
                <div className="t-meta c-primary" style={{ fontWeight: 600, fontSize: 13 }}>{activePost.rationale.rejectedCount} below threshold</div>
              </div>
            </div>
          </div>

          {/* Sources & Feedback */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16, paddingTop: 20, borderTop: '1px solid var(--border-subtle)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <span className="t-caption" style={{ fontWeight: 600 }}>Sources:</span>
              {activePost.sources.map((s, idx) => (
                <a key={idx} href={s.url} target="_blank" rel="noopener noreferrer" className="btn btn-ghost" style={{ fontSize: 12, padding: '6px 12px', borderRadius: 8, display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                  <span>{s.name}</span> <ExternalLink size={12} />
                </a>
              ))}
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <span className="t-caption" style={{ marginRight: 4, fontWeight: 600 }}>Feedback:</span>
              <button
                onClick={() => giveFeedback(activePost.id, 'liked')}
                className={`btn ${activePost.feedback === 'liked' ? 'btn-primary' : ''}`}
                style={{ borderRadius: 8, padding: '6px 12px', fontSize: 12, display: 'inline-flex', alignItems: 'center', gap: 6 }}
              >
                <ThumbsUp size={13} />
                <span>Relevant</span>
              </button>
              <button
                onClick={() => giveFeedback(activePost.id, 'disliked')}
                className={`btn ${activePost.feedback === 'disliked' ? 'btn-primary' : ''}`}
                style={{ borderRadius: 8, padding: '6px 12px', fontSize: 12, display: 'inline-flex', alignItems: 'center', gap: 6 }}
              >
                <ThumbsDown size={13} />
                <span>Not Relevant</span>
              </button>
              <button
                onClick={() => toggleBookmark(activePost.id)}
                className={`btn ${state.bookmarks.includes(activePost.id) ? 'btn-primary' : ''}`}
                style={{ borderRadius: 8, padding: '6px 10px', fontSize: 12, display: 'inline-flex', alignItems: 'center', gap: 6 }}
              >
                <Bookmark size={13} />
              </button>
            </div>
          </div>
        </article>
      )}
    </div>
  );
}
