import { useState } from 'react';
import { ThumbsUp, ThumbsDown, Sparkles, ExternalLink, TrendingUp, Rocket, Lightbulb, RefreshCw, Bookmark, FileText } from 'lucide-react';
import type { Post } from '../types';
import type { AppController } from '../hooks/useAppState';
import { timeAgo } from '../lib/format';

export function Feed({ ctrl }: { ctrl: AppController }) {
  const { state, now, giveFeedback, toggleBookmark } = ctrl;
  const [loadingNext, setLoadingNext] = useState(false);

  const fetchNextQueuedNews = async () => {
    setLoadingNext(true);
    try {
      const agentId = localStorage.getItem('navarachna_agent_id');
      if (agentId) {
        const res = await fetch(`/api/agent/publish-next?agentId=${agentId}`, { method: 'POST' });
        if (res.ok) {
          const feedData = await res.json();
          if (feedData.posts && feedData.posts.length > 0) {
            const apiPosts: Post[] = feedData.posts.map((p: any) => ({
              id: p.id,
              topicId: p.id,
              title: p.topicTitle || 'Autonomous Intelligence Update',
              domain: state.persona?.domain || 'Robotics',
              tags: [state.persona?.domain || 'Robotics', 'Live Feed', 'Autonomous'],
              whatHappened: p.text,
              whyItMatters: 'Strategic alignment with continuous discovery and editorial evaluation.',
              whatCouldHappenNext: 'Ongoing autonomous scanning will evaluate further candidate topics.',
              aiInsight: 'AI Insight: Real-time intelligence processing from live Web RSS/arXiv sources.',
              rationale: {
                whySelected: p.rationale || 'High composite score in continuous discovery scan.',
                whyRelevantNow: 'Freshly published and evaluated.',
                selectedScore: 88,
                candidatesConsidered: 8,
                rejectedCount: 7,
              },
              sources: (p.sources || ['https://arxiv.org']).map((url: string) => ({ name: 'Live Web Source', url })),
              publishedAt: p.createdAt ? new Date(p.createdAt).getTime() : Date.now(),
              feedback: null,
            }));
            ctrl.state.posts = apiPosts;
            window.dispatchEvent(new Event('storage'));
          }
        }
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoadingNext(false);
    }
  };

  const activePost = state.posts[0];

  return (
    <div style={{ maxWidth: 1100, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 32 }} className="fade-in">
      
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
        <div>
          <h1 className="t-h1 c-primary">Published Intelligence Feed</h1>
          <p className="t-body c-secondary" style={{ marginTop: 6 }}>
            Primary active report generated by autonomous continuous discovery and LLM evaluation.
          </p>
        </div>

        <button
          onClick={fetchNextQueuedNews}
          disabled={loadingNext}
          className="btn btn-primary"
          style={{ padding: '9px 16px', fontSize: 13 }}
        >
          <RefreshCw size={14} className={loadingNext ? 'animate-spin' : ''} />
          {loadingNext ? 'Publishing Next...' : 'Advance Feed Queue'}
        </button>
      </div>

      {/* Main Card */}
      {!activePost ? (
        <div className="card" style={{ padding: 48, textAlign: 'center' }}>
          <FileText size={32} className="c-muted" style={{ margin: '0 auto 12px' }} />
          <p className="t-body c-tertiary mono">No publications in feed yet. Continuous discovery engine running...</p>
        </div>
      ) : (
        <article className="card" style={{ padding: 32, background: 'var(--bg-surface)', borderColor: 'var(--border-medium)' }}>
          {/* Metadata Bar */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--border-subtle)', paddingBottom: 16, marginBottom: 24, flexWrap: 'wrap', gap: 12 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Sparkles size={16} className="c-accent" />
              <span className="t-label c-accent">PRIMARY PUBLISHED REPORT</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <span className="t-caption">{timeAgo(activePost.publishedAt, now)}</span>
              <span className="badge badge-cyan">Signal Score: {activePost.rationale.selectedScore}/100</span>
              <span className="badge badge-neutral">{activePost.domain}</span>
            </div>
          </div>

          {/* Title */}
          <h1 className="t-h1 c-primary" style={{ fontSize: 30, lineHeight: 1.25, marginBottom: 20 }}>
            {activePost.title}
          </h1>

          {/* Executive Summary Body */}
          <p className="t-body c-primary" style={{ fontSize: 16, lineHeight: 1.7, marginBottom: 32 }}>
            {activePost.whatHappened}
          </p>

          {/* 3-Column Analysis Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 20, marginBottom: 32 }}>
            <div style={{ background: 'var(--bg-inset)', padding: 20, borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                <TrendingUp size={15} className="c-highlight" />
                <span className="t-label c-highlight">Strategic Value</span>
              </div>
              <p className="t-body c-secondary" style={{ fontSize: 14, lineHeight: 1.6 }}>{activePost.whyItMatters}</p>
            </div>

            <div style={{ background: 'var(--bg-inset)', padding: 20, borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                <Rocket size={15} className="c-success" />
                <span className="t-label c-success">Trajectory &amp; Impact</span>
              </div>
              <p className="t-body c-secondary" style={{ fontSize: 14, lineHeight: 1.6 }}>{activePost.whatCouldHappenNext}</p>
            </div>

            <div style={{ background: 'var(--bg-inset)', padding: 20, borderRadius: 12, border: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                <Lightbulb size={15} className="c-warning" />
                <span className="t-label c-warning">Autonomous Assessment</span>
              </div>
              <p className="t-body c-secondary" style={{ fontSize: 14, lineHeight: 1.6 }}>{activePost.aiInsight.replace('AI Insight: ', '')}</p>
            </div>
          </div>

          {/* Editorial Rationale Box */}
          <div style={{ background: 'var(--bg-card)', padding: 20, borderRadius: 12, border: '1px solid var(--border-subtle)', marginBottom: 28 }}>
            <div className="t-label c-tertiary" style={{ marginBottom: 12 }}>System Editorial Audit</div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16 }}>
              <div>
                <div className="t-caption">Why Selected</div>
                <div className="t-meta c-primary" style={{ marginTop: 2 }}>{activePost.rationale.whySelected}</div>
              </div>
              <div>
                <div className="t-caption">Recency Context</div>
                <div className="t-meta c-primary" style={{ marginTop: 2 }}>{activePost.rationale.whyRelevantNow}</div>
              </div>
              <div>
                <div className="t-caption">Candidates Evaluated</div>
                <div className="t-meta c-primary" style={{ marginTop: 2 }}>{activePost.rationale.candidatesConsidered} candidate topics</div>
              </div>
              <div>
                <div className="t-caption">Filtered Candidates</div>
                <div className="t-meta c-primary" style={{ marginTop: 2 }}>{activePost.rationale.rejectedCount} below threshold</div>
              </div>
            </div>
          </div>

          {/* Sources & Feedback */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16, paddingTop: 20, borderTop: '1px solid var(--border-subtle)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <span className="t-caption">Sources:</span>
              {activePost.sources.map((s, idx) => (
                <a key={idx} href={s.url} target="_blank" rel="noopener noreferrer" className="btn btn-ghost" style={{ fontSize: 12, padding: '4px 8px' }}>
                  {s.name} <ExternalLink size={11} />
                </a>
              ))}
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span className="t-caption" style={{ marginRight: 4 }}>Feedback:</span>
              <button
                onClick={() => giveFeedback(activePost.id, 'liked')}
                className={`btn ${activePost.feedback === 'liked' ? 'btn-primary' : ''}`}
              >
                <ThumbsUp size={13} /> Relevant
              </button>
              <button
                onClick={() => giveFeedback(activePost.id, 'disliked')}
                className="btn"
              >
                <ThumbsDown size={13} /> Not Relevant
              </button>
              <button
                onClick={() => toggleBookmark(activePost.id)}
                className={`btn ${state.bookmarks.includes(activePost.id) ? 'btn-primary' : ''}`}
              >
                <Bookmark size={13} />
              </button>
            </div>
          </div>
        </article>
      )}
    </div>
  );
}
